### PR TITLE
devon modules migration and spring boot upgrade

### PR DESCRIPTION
**Pull request by Rohit90700**
Microservices-archtype testing is pending ,just created for sharing.

### CODE REVIEW

**Comment by Rohit90700** [comment]
i did not changed .adoc and .txt files (CODE_OF_CONDUCT.adoc , CONTRIBUTING_GUIDE.adoc ,terms-of-use.txt).

**Comment by AbhayChandel** [comment]
** Please DON'T MERGE ** 

Tasks related to this PR are in progress.

**Comment by pablo-parra** [comment]
Hi, as far as I have reviewed seems that the core of the changes is related to versions and naming so I have focused on functionality. I was able to launch all the infrastructure services and a sample microservice without issues, the only thing I missed was a change in the devonfw parent pom <devonfw.version> property  (it is still marked as 2.4.0, what broke other microservices projects I have btw). Regarding the functionality I have noticed that now when no authenticated request is done the error thrown appears in html format and is not too descriptive (I think in previous versions the error message was more concrete). I guess it is not directly related with those particular PRs but a previous changes in the modules, but maybe it could be treated as a future improvement.

**Comment by vapadwal** [comment]
Yes we will change <devonfw.version>  in root pom to 3.0.0 while making the release. For other issue mentioned we will create issue and solve it in future releases

**Pull request merged**
